@NetRentManagerApi_HostAddress = http://localhost:5065

POST {{NetRentManagerApi_HostAddress}}/api/properties
Content-Type: multipart/form-data; boundary=CreatePropertyBoundary

--CreatePropertyBoundary
Content-Disposition: form-data; name="title"

Apartamento nuevo
--CreatePropertyBoundary
Content-Disposition: form-data; name="description"

Descripción de prueba
--CreatePropertyBoundary
Content-Disposition: form-data; name="address"

Calle Principal 10
--CreatePropertyBoundary
Content-Disposition: form-data; name="price"

1200
--CreatePropertyBoundary
Content-Disposition: form-data; name="status"

Available
--CreatePropertyBoundary
Content-Disposition: form-data; name="bedroomCount"

2
--CreatePropertyBoundary
Content-Disposition: form-data; name="bathroomCount"

1
--CreatePropertyBoundary
Content-Disposition: form-data; name="areaSquareMeters"

70
--CreatePropertyBoundary--
Accept: application/json

###

@PropertyWithImageId = 00000000-0000-0000-0000-000000000001
@PropertyWithoutImageId = 00000000-0000-0000-0000-000000000002

GET {{NetRentManagerApi_HostAddress}}/api/properties/{{PropertyWithImageId}}
Accept: application/json

###

GET {{NetRentManagerApi_HostAddress}}/api/properties/{{PropertyWithoutImageId}}
Accept: application/json

###

GET {{NetRentManagerApi_HostAddress}}/api/properties/00000000-0000-0000-0000-000000000099
Accept: application/json

###

GET {{NetRentManagerApi_HostAddress}}/api/properties/no-es-guid
Accept: application/json

###

@PropertyId = a1f0e2d4-7c81-4d12-9e61-0b7f0b1a1001

PATCH {{NetRentManagerApi_HostAddress}}/api/properties/{{PropertyId}}/status
Content-Type: application/json
Accept: application/json

{
	"status": "rented"
}

###

PUT {{NetRentManagerApi_HostAddress}}/api/properties/{{PropertyId}}
Content-Type: multipart/form-data; boundary=UpdatePropertyBoundary

--UpdatePropertyBoundary
Content-Disposition: form-data; name="title"

Apartamento actualizado
--UpdatePropertyBoundary
Content-Disposition: form-data; name="description"

Descripción actualizada
--UpdatePropertyBoundary
Content-Disposition: form-data; name="address"

Calle Principal 10
--UpdatePropertyBoundary
Content-Disposition: form-data; name="price"

1250
--UpdatePropertyBoundary
Content-Disposition: form-data; name="status"

Available
--UpdatePropertyBoundary
Content-Disposition: form-data; name="bedroomCount"

2
--UpdatePropertyBoundary
Content-Disposition: form-data; name="bathroomCount"

1
--UpdatePropertyBoundary
Content-Disposition: form-data; name="areaSquareMeters"

70
--UpdatePropertyBoundary--
Accept: application/json

###

PUT {{NetRentManagerApi_HostAddress}}/api/properties/{{PropertyId}}
Content-Type: multipart/form-data; boundary=UpdatePropertyImageBoundary

--UpdatePropertyImageBoundary
Content-Disposition: form-data; name="title"

Apartamento con imagen actualizada
--UpdatePropertyImageBoundary
Content-Disposition: form-data; name="description"

Descripción actualizada con imagen
--UpdatePropertyImageBoundary
Content-Disposition: form-data; name="address"

Calle Principal 11
--UpdatePropertyImageBoundary
Content-Disposition: form-data; name="price"

1300
--UpdatePropertyImageBoundary
Content-Disposition: form-data; name="status"

Available
--UpdatePropertyImageBoundary
Content-Disposition: form-data; name="bedroomCount"

2
--UpdatePropertyImageBoundary
Content-Disposition: form-data; name="bathroomCount"

2
--UpdatePropertyImageBoundary
Content-Disposition: form-data; name="areaSquareMeters"

80
--UpdatePropertyImageBoundary
Content-Disposition: form-data; name="image"; filename="property.png"
Content-Type: image/png

< .\support\seed-data\images\properties\1.png
--UpdatePropertyImageBoundary--
Accept: application/json

###
